version: '3'
services:
  database:
    # Dockerfile이 있는 위치 
    #build: ./database
    image: cloudydong/testapp:database
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    volumes:
      - ./database/own:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
  backend:
    #build: ./backend
    image: cloudydong/testapp:backend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    restart: always
    # 환경변수 설정
    environment: 
      - DBHOST=database
  frontend:
    #build: ./frontend
    image: cloudydong/testapp:frontend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    restart: always
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"